### PR TITLE
Use -coverpkg flag in go test

### PR DESCRIPTION
**Pull request by jacklee1792**
The last commit is there to test that the test in `test-pkg` counts towards coverage. It can be removed. With the last commit,

- `go test -covermode count ./...` has 40% coverage.
- `go test -covermode count -coverpkg ./... ./...` has 80% coverage.

### CODE REVIEW

**Comment by shinenelson** [comment]
Hey @jacklee1792, this is amazing. I came here looking for the same feature in this action and I found your pull request. Do you think it would be a good idea to make the `-coverpkg` flag configurable so that people who wants to cover only specific packages can use it as an input according to their needs as well?

**Comment by gwatts** [comment]
@jacklee1792 thanks for the PR!  

Might be nice to omit the `coverpkg` arg completely if it's been set to blank or `none`

**Review by gwatts — APPROVED** [review]
Thanks @jacklee1792 !

**Comment by shinenelson** [comment]
could @gwatts please _release_ this so that people can benefit from this?

**Comment by gwatts** [comment]
@shinenelson yep this has been released as 1.2.0 now

**Comment by shinenelson** [comment]
Thank you very much @gwatts. I am going to include this in my workflows right away 🚢 :shipit: 🚀

**Pull request merged**
